version: '3.9'

services:
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_HOST=${DATASOURCE_HOST}
      - DATASOURCE_PORT=${DATASOURCE_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3300:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}



