------------------------------------------------
-- Table: public.users
------------------------------------------------

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    patronymic character varying(255) COLLATE pg_catalog."default",
    surname character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
    )
    WITH (
        OIDS = FALSE
        )
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

INSERT INTO public.users (name, surname, patronymic)
    VALUES ('Таисия', 'Кузьмина', 'Данииловна');

INSERT INTO public.users (name, surname, patronymic)
    VALUES ('Владимир', 'Борисов', 'Алексеевич');

INSERT INTO public.users (name, surname, patronymic)
    VALUES ('Илья', 'Борисов', 'Кириллович');

INSERT INTO public.users (name, surname, patronymic)
    VALUES ('Иван', 'Романович', 'Романович');

INSERT INTO public.users (name, surname, patronymic)
    VALUES ('Лев', 'Степанов', 'Дмитриевич');

INSERT INTO public.users (name, surname, patronymic)
    VALUES ('Иван', 'Сидоров', 'Кириллович');

INSERT INTO public.users (name, surname, patronymic)
    VALUES ('Ульяна', 'Попова', 'Фёдоровна');
