------------------------------------------------
-- Table: public.staff
------------------------------------------------

CREATE TABLE IF NOT EXISTS public.staff
(
    medical_staff_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    end_work_time time without time zone,
    experience integer,
    profession character varying(255) COLLATE pg_catalog."default",
    start_work_time time without time zone,
    user_user_id integer,
    CONSTRAINT staff_pkey PRIMARY KEY (medical_staff_id),
    CONSTRAINT fk7ce78nq4kr0q9afwv1wmbs9ge FOREIGN KEY (user_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
                       ON UPDATE NO ACTION
                       ON DELETE NO ACTION
    )
                       WITH (
                           OIDS = FALSE
                           )
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.staff
    OWNER to postgres;

INSERT INTO public.staff (description, end_work_time, experience, profession, start_work_time, user_user_id)
    VALUES ('Какое то описание', '08:15:00', 5, 'SURGEON', '21:00:00', 1);

INSERT INTO public.staff (description, end_work_time, experience, profession, start_work_time, user_user_id)
    VALUES ('Какое то описание', '08:15:00', 3, 'THERAPIST', '21:00:00', 3);

INSERT INTO public.staff (description, end_work_time, experience, profession, start_work_time, user_user_id)
    VALUES ('Какое то описание', '08:15:00', 1, 'UROLOGIST', '21:00:00', 5);

INSERT INTO public.staff (description, end_work_time, experience, profession, start_work_time, user_user_id)
    VALUES ('Какое то описание', '08:15:00', 1, 'SURGEON', '21:00:00', 7);
