------------------------------------------------
-- Table: public.user_credence
------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_credence
(
    credence_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    login character varying(255) COLLATE pg_catalog."default",
    mail character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    user_user_id integer,
    CONSTRAINT user_credence_pkey PRIMARY KEY (credence_id),
    CONSTRAINT fkfhnbsn7pdrgq4bt71v8v7vk52 FOREIGN KEY (user_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )
    WITH (
        OIDS = FALSE
        )
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_credence
    OWNER to postgres;

INSERT INTO public.user_credence (login, mail, password, phone, user_user_id)
    VALUES ('aboba', 'aboba@gmail.com', '$2a$12$5.4WPJOLQoAnMJmdUhSl1e88OLtu.rMJWHqRuu4tVY2o/nkot8YN.', '7843138773579', 1);

INSERT INTO public.user_credence (login, mail, password, phone, user_user_id)
    VALUES ('abiba', 'abiba@gmail.com', '$2a$12$wS1Z3dim1QxH0iSAEFodgOFH8ync3ueVPIN5lnfPcmmvzVSYeZKZO', '7848918773579', 2);

INSERT INTO public.user_credence (login, mail, password, phone, user_user_id)
    VALUES ('mora', 'mora@gmail.com', '$2a$12$p5zxnzpwb98w2mLL85Nzo.Z.Yne/EtyCalDNoSKNDedos22xBErg6', '7848487273579', 3);

INSERT INTO public.user_credence (login, mail, password, phone, user_user_id)
    VALUES ('estes', 'estes@gmail.com', '$2a$12$V7.8Aymz3AGARYkVUJ4f1usXHt4JvKGpy032Stu2hUm5qOOfFP68K', '7847318773579', 4);

INSERT INTO public.user_credence (login, mail, password, phone, user_user_id)
    VALUES ('volk', 'volk@gmail.com', '$2a$12$L4kTBJEBjcLFVF8nX7/oF.S2bT7KnWKK0C99KpUNbn4EQi2fyS2dm', '7848914293579', 5);

INSERT INTO public.user_credence (login, mail, password, phone, user_user_id)
    VALUES ('noname', 'noname@gmail.com', '$2a$12$O/6OeWewA7dmPzUUYPz/JOZVOir7JKs1ho11d/1zC66.BxqfSAwia', '7848328773579', 6);

INSERT INTO public.user_credence (login, mail, password, phone, user_user_id)
    VALUES ('gamora', 'gamora@gmail.com', '$2a$12$7YbstqwQIhSyssOpn1RTl.Fhn4V6BZddr4xYf7ELRMivGYTYxuv4i', '7848988773579', 7);
