------------------------------------------------
-- Table: public.medical_card_entry
------------------------------------------------

CREATE TABLE IF NOT EXISTS public.medical_card_entry
(
    medical_card_entry_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    conclusion character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    disease_name character varying(255) COLLATE pg_catalog."default",
    medical_comment character varying(255) COLLATE pg_catalog."default",
    card_id integer,
    CONSTRAINT medical_card_entry_pkey PRIMARY KEY (medical_card_entry_id),
    CONSTRAINT fk1752g199bhjnxlab7r97503f6 FOREIGN KEY (card_id)
        REFERENCES public.medical_cards (card_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.medical_card_entry
    OWNER to postgres;

INSERT INTO public.medical_card_entry (conclusion, description, disease_name, medical_comment, card_id)
    VALUES ('', '', '', '', 1);

INSERT INTO public.medical_card_entry (conclusion, description, disease_name, medical_comment, card_id)
    VALUES ('Мне лень', 'хм хм', 'Ну такое', 'И тебя вылечат и меня вылечат', 2);

INSERT INTO public.medical_card_entry (conclusion, description, disease_name, medical_comment, card_id)
    VALUES ('Придумывай сам', 'Я описание', 'Деменция', 'И тебя вылечат и меня вылечат', 3);