------------------------------------------------
-- Table: public.appointment_entry
------------------------------------------------

CREATE TABLE IF NOT EXISTS public.appointment_entry
(
    appointment_entry_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    appointment_status character varying(255) COLLATE pg_catalog."default" DEFAULT 'NOT_STARTED'::character varying,
    date date,
    medic_comment character varying(255) COLLATE pg_catalog."default",
    patient_status character varying(255) COLLATE pg_catalog."default" DEFAULT 'NONE'::character varying,
    "time" time without time zone,
    medic_id integer,
    patient_id integer,
    CONSTRAINT appointment_entry_pkey PRIMARY KEY (appointment_entry_id),
    CONSTRAINT fk38s8ubtoq4dy6era8rxru9ekq FOREIGN KEY (patient_id)
    REFERENCES public.patient (patient_id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION,
    CONSTRAINT fkj0e7esx59598mtf4smslch02k FOREIGN KEY (medic_id)
    REFERENCES public.staff (medical_staff_id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
    )
                WITH (
                    OIDS = FALSE
                    )
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.appointment_entry
    OWNER to postgres;

